### PR TITLE
Update api.js

### LINKED ISSUE #35: doest work for me anymore
This was working for a long time, then recently (within the last week) I get this, repeatedly, over and over.... 

[2018-6-3 23:48:12] [House Side Garage Door] Error: Error processing request (217)
at fetch.then.then.data (/usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:26:29)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:118:7)

Thanks if anyone can look into it.  I've tried reloading, removing accessories and let it error out(thinking maybe my deviceIDs changed) nothing.  Just will not work anymore.

### PR DESCRIPTION
**Pull request by mattwillems**
Fixes #35 by updating the referenced iOS version.

### CODE REVIEW

**Comment by caseywebdev** [comment]
Any reason to not just bump it all the way to `12.0.0`?

**Comment by mattwillems** [comment]
Probably not, I just didn't have a chance to test that.

**Comment by mattwillems** [comment]
Also now I do seem to get that error on startup, but not on polling and functionality is restored.

**Comment by janthony6** [comment]
I bumped mine up to 12.2.0 and that seems to have fixed the errors.  

I also changed the Chamberlain version to the latest version 3.120

'User-Agent': 'Chamberlain/3.120 (iPhone; iOS 12.2.0; Scale/2.00)',

**Review by janthony6 — CHANGES_REQUESTED** [review]
'User-Agent': 'Chamberlain/3.120 (iPhone; iOS 12.2.0; Scale/2.00)',

I wonder if the API Version can be bumped up?  4.1? is that Android?  Maybe 5.0?

**Comment by tastheimer** [comment]
This should be approved and merged. After manually applying this change the ECONRESET error is no longer occuring

**Pull request merged**
