### PR TITLE
Add Config Schema

### PR DESCRIPTION
**Pull request by dereklucas**
Enables a nice settings screen in Homebridge Config UI X, per https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI

### CODE REVIEW

**Comment by iRayanKhan** [comment]
I’ll take a look at this tonight and merge it after some testing. Thanks for contributing! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
If anyone can test this and give me a green light I'll merge it in!

**Comment by dereklucas** [comment]
Weird, replying to the GitHub email didn’t post it here:

There’s a schema tester here: https://hamidihamza.com/Angular6-json-schema-form/?framework=bootstrap-4 that doesn’t complain about any errors, but unfortunately I couldn’t get NPM to install directly from my branch, so I couldn’t actually test it within homebridge-config-x.

**Comment by iRayanKhan** [comment]
I might merge this today as the plugin needs an update to force an api.js file update. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by iRayanKhan — APPROVED** [review]
Looks good, merging now.

**Comment by dereklucas** [comment]
Managed to get it installed (turns out NPM can install a package without git by pointing it at the `/tarball` url) and it looks good. Even lets you add multiple doors properly, which is cool. (You still need to find the Device IDs in the log for that though.)

Screen Shot 2019-10-25 at 2 15 28 PM

**Pull request merged**
